name: mycontacts
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  core:
    path: module/core
  uikit:
    path: module/uikit

  welcome:
    path: feature/welcome
  auth:
    path: feature/auth
  dashboard:
    path: feature/dashboard

  cupertino_icons: ^1.0.8
  envied: ^0.3.0+3
  go_router: ^14.6.2
  get_it: ^8.0.3
  easy_localization: ^3.0.7
  sliver_tools: ^0.2.12
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.16
  shimmer: ^3.0.0
  firebase_messaging: ^15.1.6
  firebase_core: ^3.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  envied_generator: ^0.3.0+3
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/translations/
